version: '3.8'

services:
  node-red:
    image: nodered/node-red:3.1.8-debian
    container_name: node-red
    ports:
      - 1880:1880
    volumes:
      - node-red-data:/data
  minio:
    image: quay.io/minio/minio:RELEASE.2024-04-06T05-26-02Z.fips
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    env_file:
      - .env
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    
volumes:
  node-red-data:
  minio-data: